### PR TITLE
Fix Python 3 compatibility

### PR DESCRIPTION
**Pull request by pinkavaj**
This should allow run in both python 2 & 3, I does not have py2 installed so inly python3 is tested.

### CODE REVIEW

**Comment by pinkavaj** [comment]
Fails on `ERROR: InterpreterNotFound: python2.6`, thats something I cannot fix, can You please help?

**Comment by flyte** [comment]
Thanks for the PR! That error just means you don't have python 2.6 installed. To be honest I'm not interested in supporting python 2.6 anyway, so 2.7 support is sufficient.

I'm on holiday right now so I can't test, but when I get back I can double check and merge the PR. 

Cheers

**Comment by pinkavaj** [comment]
This looks like python2.6 environment is missing in Travis. meybe first remove Python 2.6 supporte (See my other MR), the I can add test support for Python 3 into this MR, so we can be sure combatibility is not broken in future?

**Comment by pinkavaj** [comment]
We can consider to add test for both python 3.4 and 3.7 (3.8) to cover the minimal and maximal supported python 3 version.

Of cource MR #2 should be merged first.

**Comment by pinkavaj** [comment]
Should be over develop now.

**Comment by flyte** [comment]
LGTM, thanks! :1st_place_medal:

**Pull request merged**
